import { Button, VerticalBox, HorizontalBox, StandardListView } from "std-widgets.slint";

component ImageViewer inherits Rectangle{
    in property <image> image;
            
            width: 512px;
            height: 512px;
            background: #202126;
            border-radius: 7px;
        
            Image {
                source: image;
                image-fit: contain;
                width: parent.width * 0.95;
                height: parent.height * 0.95;
            }
}

component ImageTile inherits Rectangle {
    in property <bool> selected;
    in property <image> preview_smol;
    in property <string> image_name;
    
    background: #202126;
    border-radius: 7px;
    height: 128px;

    VerticalBox {
        
        Image {
            source: preview_smol;
            image-fit: contain;
            width: parent.width * 0.95;
            height: parent.height * 0.95;
        }
        Text {
            horizontal-alignment: center;
            text: image_name;
        }
    }
    
}

export component AppWindow inherits Window {
    callback openFileSelector;
    in property <image> image;
    in property <[string]> image_names;

    HorizontalBox {
        VerticalBox {
            width: 256px;
            Button {
                height: 32px;
                
                text: "Open File Selector";
                clicked => {root.openFileSelector();}
            }
            VerticalBox {
                for img_name in image_names: ImageTile {
                    image_name: img_name;
                }
            }
        }

        VerticalBox {   
            padding-bottom: 20px;
            ImageViewer {
                image: image;
            }
        }
    }
    
}
