component ImageTile inherits Rectangle {

    in property <bool> selected;
    in property <image> preview_smol;
    in property <string> image_name;
    in-out property <int> id;
    
    background: Palette.bg1;
    border-radius: 7px;
    height: 128px;

    TouchArea {
        clicked => {Logic.clickedImageTile(id)}
        VerticalLayout {
            Image {
                source: preview_smol;
                image-fit: contain;
                width: parent.width * 0.95;
                height: parent.height * 0.95;
            }
            Rectangle {
                width: parent.width;
                height: 16px;
                border-radius: 7px;
                border-width: 1px;
                border-color: selected ? Palette.bg2 : Palette.bg3;
                background: Palette.bg2;
    
                Text {
                    horizontal-alignment: center;
                    text: image_name;
                }
            }   
        }
    }   
}